### ISSUE TITLE
Dplyr joins fail when tinylabels is not loaded

### ISSUE THREAD

**Issue by ottothecow** [mariusbarth/tinylabels#3]
I've run into an interesting bug when working with datasets that are loaded from RDS format.  I prepared the data in one program and tried to use tinylabels to label the variables before saving the RDS file where it could be used by others.  I assumed that people would be able to read and work with these datasets without issue since tidylabels just sets an attribute (much like the way other libraries handle labels).  

However, it seems that if you don't load the tinylabels package, dplyr won't understand what to do with the labelled columns.  For example, if you try to join a labelled dataset with an unlabelled dataset, it will fail with an "incompatible types" error.

Here's an attempt at an example that reproduces.  First run this code in a fresh R session (set working directory as needed)
```
library(dplyr)
library(tinylabels)

dfA = tibble(id = as.character(1:5),
             valA = 1: 5*2)
dfB = tibble(id = as.character(1:5),
             valB = 1: 5*3) %>%
  label_variables(id='Identifier',
                  valB = 'Value')

test1 = dfA %>% left_join(dfB)

saveRDS(dfA,'A.RDS')
saveRDS(dfB,'B.RDS')
```
Then restart R and run this code (again with same working directory)

```
library(dplyr)

dfA = readRDS('A.RDS')
dfB = readRDS('B.RDS')
test2 = dfA %>% left_join(dfB)
```
it will fail like this:

```
> test2 = dfA %>% left_join(dfB)
Joining with `by = join_by(id)`
Error in `left_join()`:
! Can't join `x$id` with `y$id` due to incompatible types.
ℹ `x$id` is a <character>.
ℹ `y$id` is a <tiny_labelled>.
```

I'm new to this library so I don't have any idea of how to best fix this, or if it even should be fixed, but, in my view, it would be nice if the labelling were able to persist even when the library is not loaded.  I plan to do some further testing with other methods of labelling variables in R, as I don't recall ever having a similar issue in the past when working with labelled data using other libraries.

**Comment by mariusbarth** [comment]
Hi @ottothecow, 

this is indeed an interesting issue that is most likely caused by the fact that tinylabels' `vec_ptype2` and `vec_cast` methods are (only) dynamically registered when the package is loaded. The reason for this design choice is that the tidyverse is supported, but no dependency to the **vctrs** package is introduced. However, I think what you describe here is a standard use case for variable labels, and should thus be possible without head scratching. I will give it a bit of thought -- a fix would be to statically register the above-mentioned methods, but maybe there is a better option.

**Comment by mariusbarth** [comment]
Hi @ottothecow,

I dug a bit deeper into this issue and figured that the same problem arises with other *labelled* vector classes, such as those created from **haven**. Here is a minimal reproducible example using **haven**:

```
library(dplyr)
library(haven)

dfA <- tibble(id = as.character(1:5),
             valA = 1: 5*2)
dfB <- tibble(id = labelled(as.character(1:5), label = "Identifier"))
             valB = labelled(1: 5*3, label = "Value B"))
saveRDS(dfA, "~/dfA.rds")
saveRDS(dfB, "~/dfB.rds")

left_join(dfA, dfB)
```
returns
```
Joining with `by = join_by(id)`
# A tibble: 5 × 2
  id         valA
  <chr+lbl> <dbl>
1 1             2
2 2             4
3 3             6
4 4             8
5 5            10
```

But in a vanilla R session
```
library(dplyr)
dfA <- readRDS('~/dfA.rds')
dfB <- readRDS('~/dfB.rds')
left_join(dfA, dfB)
```
fails with the same error
```
Joining with `by = join_by(id)`
Error in `left_join()`:
! Can't join `x$id` with `y$id` due to incompatible types.
ℹ `x$id` is a <character>.
ℹ `y$id` is a <haven_labelled>.
Run `rlang::last_trace()` to see where the error occurred.
```

So I consider this to be a **dplyr** issue. I am not sure if this is a bug or a design choice (made in the **vctrs** package). Maybe @hadley has a good idea how to deal with this problem?

**Comment by ottothecow** [comment]
I think you are right.  I thought I recalled this working with other libraries, but the examples I could find all still had haven loaded.

I note that the base R merge() function seems to work:

In a vanilla R session after running the code above to create dfA.rds and dfB.rds:
```
dfA <- readRDS('~/dfA.rds')
dfB <- readRDS('~/dfB.rds')

merge(dfA, dfB, by='id')
```
returns:
```
  id valA valB
1  1    2    3
2  2    4    6
3  3    6    9
4  4    8   12
5  5   10   15
```

Which is as expected.

So this seems like it may actually be a dplyr bug.  Somewhere dplyr should probably be checking the parent class for compatibility.  

My guess is that labelled vectors aren't the only special types that run into this problem, but it creates an issue for data portability.

**Comment by ottothecow** [comment]
Update: I can make it work without loading a package if I do something like this:

```
library(dplyr)

dfA <- tibble(id = as.character(1:5),
              valA = 1: 5*2)
dfB <- tibble(id = as.character(1:5),
              valB = 1: 5*3)

attr(dfB$id, "label") <- "Identifier"
attr(dfB$valB, "label") <- "Value B"

saveRDS(dfA, "~/dfA.rds")
saveRDS(dfB, "~/dfB.rds")

left_join(dfA, dfB)
```
returns:
```
Joining, by = "id"
# A tibble: 5 × 3
  id     valA  valB
  <chr> <dbl> <dbl>
1 1         2     3
2 2         4     6
3 3         6     9
4 4         8    12
5 5        10    15
```
then in a vanilla R session:

```
library(dplyr)

dfA <- readRDS('~/dfA.rds')
dfB <- readRDS('~/dfB.rds')

left_join(dfA, dfB)
```
Returns:
```
Joining, by = "id"
# A tibble: 5 × 3
  id     valA  valB
  <chr> <dbl> <dbl>
1 1         2     3
2 2         4     6
3 3         6     9
4 4         8    12
5 5        10    15
```

But the label attribute is preserved if you view the dataframe in RStudio, and it shows up with something like ```str(dfB)```

I think this is as expected--the problem here is not the label attribute itself but rather that **dplyr** doesn't know what to do with the vector when its class is ```"haven_labelled"``` or ```"tiny_labelled"``` but **haven** or **tinylabels** has not been loaded.

So I do think this is a **dplyr/vctrs** bug, but I must ask: is it necessary to cast the series as tiny_labelled? Could the same be accomplished by just setting/checking for the label attribute?  (I could be way off here, just spitballing)

**Comment by hadley** [comment]
I don't think this is a dplyr issue; it's fundamental problem with the way that serialisation works in R. There's no information in what `saveRDS()` records that indicates it's necessary to load tinylabels in order to actually work with the datasets that you have loaded, so this is something you have to handle yourself.

**Comment by mariusbarth** [comment]
Thank you for your swift response! Agreed 👍
